name: Test build of geostyler-cql-parser

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Use bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies ⏬
      run: bun install

    - name: Test code ✅
      run: bun test --coverage --coverage-reporter=lcov

    - name: Build artifacts 🏗️
      run: bun run build

    - name: Publish to coveralls ⭐
      # coverage/lcov.info was generated in the previous npm run build step
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
